/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.redes1parcial2semestre.cursoreact;

import com.redes.conexion.Conexion;
import com.redes.estudiantes.StudentsForm;
import com.redes.verificacion.Imagenes;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JIMAZO
 */
public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form SignupForm
     */
    public SignupForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jUsuario = new javax.swing.JTextPane();
        jContraseña = new javax.swing.JPasswordField();
        jBCancelar = new javax.swing.JButton();
        ver = new javax.swing.JCheckBox();
        jBIniciar = new javax.swing.JButton();
        jUsuarioNuevo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(189, 195, 199));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(253, 227, 167));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 14, 44));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 14, 44));
        jLabel1.setText("Iniciar Sesión");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 18, 270, 50));

        minimizar.setText("-");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 0, 11, -1));

        Cerrar.setText("x");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        jPanel1.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.setForeground(new java.awt.Color(8, 14, 44));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usuario.setText("Usuario:");
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        contraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseña.setText("Contraseña:");
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jScrollPane2.setViewportView(jUsuario);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 149, -1));

        jContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 149, 30));

        jBCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, -1));

        ver.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        ver.setText("Ver");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        jPanel2.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 60, 20));

        jBIniciar.setBackground(new java.awt.Color(255, 255, 255));
        jBIniciar.setForeground(new java.awt.Color(0, 0, 0));
        jBIniciar.setText("Iniciar");
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });
        jPanel2.add(jBIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, -1));

        jUsuarioNuevo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jUsuarioNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jUsuarioNuevo.setText("¿Usuario nuevo? Registrate aquí");
        jUsuarioNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jUsuarioNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUsuarioNuevoMouseClicked(evt);
            }
        });
        jPanel2.add(jUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 230, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked

        setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_minimizarMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void jContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContraseñaActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // ODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
        if(ver.isSelected() ){
            jContraseña.setEchoChar ((char)0);
        }else{
            jContraseña.setEchoChar (('*'));
            
        }
    }//GEN-LAST:event_verActionPerformed

    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarActionPerformed
        // TODO add your handling code here:
        Conexion conexion=new Conexion();
        try {
            Connection conn=conexion.getConnection();
            PreparedStatement stmt=conn.prepareStatement("SELECT * FROM usuarios WHERE usuario=? AND contraseña=SHA1(?)");
            stmt.setString(1,jUsuario.getText());
            stmt.setString(2,String.copyValueOf(jContraseña.getPassword()));
            ResultSet rs=stmt.executeQuery();
            if(rs.next()==true){
                //JOptionPane.showMessageDialog(null, "LOGIN EXITOSO");
                StudentsForm student=new StudentsForm();
                student.setVisible(true);
                StudentsForm.idUserLog=rs.getInt(1);
                dispose();
                Imagenes img=new Imagenes();
                student.jUserImgLog.setIcon(img.redimensionPicture(null,rs.getBytes(6),student.jUserImgLog.getWidth(),student.jUserImgLog.getHeight()));
                student.jUsuarioLog.setText(rs.getString(4));
                student.idUserLog=rs.getInt(1);
                
            }else{
                JOptionPane.showMessageDialog(null, "CONTRASEÑA O USUSARIO INCORRECTO");
                jUsuario.setText("");
                jContraseña.setText("");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        
    }//GEN-LAST:event_jBIniciarActionPerformed

    private void jUsuarioNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsuarioNuevoMouseClicked
        // TODO add your handling code here:
        SignUp signupf=new SignUp();
        signupf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jUsuarioNuevoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBIniciar;
    private javax.swing.JPasswordField jContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jUsuario;
    private javax.swing.JLabel jUsuarioNuevo;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel usuario;
    private javax.swing.JCheckBox ver;
    // End of variables declaration//GEN-END:variables
}
