/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.redes.estudiantes;

import com.redes.conexion.Conexion;
import com.redes.verificacion.Imagenes;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
/**
 *
 * @author JIMAZO
 */
public class StudentsForm extends javax.swing.JFrame {

    String imagenPath;
    byte[] img=null;
    public static int idUserLog;
    
    DefaultTableModel model=new DefaultTableModel();
    public StudentsForm() {
        initComponents();
        retornarTabla();
        setLocationRelativeTo(null);
        jTableListaEst.setModel(model);
        model.addColumn("ID");
        model.addColumn("NOMBRE");
        model.addColumn("APELLIDO");
        model.addColumn("NIVEL");
        model.addColumn("TELEFONO");
        model.addColumn("EMAIL");
        model.addColumn("DIRECCION");
        model.addColumn("IMAGEN");
        jTableListaEst.setShowGrid(true);
        jTableListaEst.setRowHeight(60);
        jTableListaEst.setGridColor(Color.black);
        
        JTableHeader th=jTableListaEst.getTableHeader();
        th.setForeground(Color.WHITE);
        th.setFont(new Font("Tahoma", Font.CENTER_BASELINE, 14));
        
        listarEstudiantes();
        System.out.println("Id User: "+idUserLog);
    }
    
    public void listarEstudiantes(){
        EstudiantesQuery query=new EstudiantesQuery();
        ArrayList<Estudiante> estudiantes=query.listarEstudiante(idUserLog);
        ImageIcon img;
        for (int i = 0; i < estudiantes.size(); i++){
            model.addRow(new Object[]{
                estudiantes.get(i).getIdEstudiante(),
                estudiantes.get(i).getNombre(),
                estudiantes.get(i).getApellido(),
                estudiantes.get(i).getNivel(),
                estudiantes.get(i).getTelefono(),
                estudiantes.get(i).getCorreo(),
                estudiantes.get(i).getDireccion(),
                img = new ImageIcon(new ImageIcon(estudiantes.get(i).getImagen()).getImage().getScaledInstance(60,50,Image.SCALE_SMOOTH)),
            });
            
        }
    }
    
    public void retornarTabla(){
        model=new DefaultTableModel(){
            //@Override
            public Class getColumnClass(int columna){
                if(columna==7){
                    return ImageIcon.class;
                }else{
                    return Object.class;
                }
            }
        };
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        Cerrar = new javax.swing.JLabel();
        jUsuarioLog = new javax.swing.JLabel();
        jUserImgLog = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTelefono = new javax.swing.JTextPane();
        jBCancelar = new javax.swing.JButton();
        jAgregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDireccion = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jApellido = new javax.swing.JTextPane();
        contraseña1 = new javax.swing.JLabel();
        contraseña2 = new javax.swing.JLabel();
        contraseña3 = new javax.swing.JLabel();
        jNivel = new javax.swing.JComboBox<>();
        usuario1 = new javax.swing.JLabel();
        usuario2 = new javax.swing.JLabel();
        jImagenEst = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jCorreo = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jNombre1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaEst = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 227, 167));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(8, 14, 44));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 14, 44));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("curso react");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 630, 50));

        minimizar.setText("-");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel1.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 10, -1));

        Cerrar.setText("x");
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });
        jPanel1.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        jUsuarioLog.setForeground(new java.awt.Color(0, 0, 0));
        jUsuarioLog.setText("Usuario");
        jPanel1.add(jUsuarioLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jUserImgLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jUserImgLog.setOpaque(true);
        jPanel1.add(jUserImgLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Imagen:");
        jPanel3.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        contraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("correo:");
        jPanel3.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jTelefono.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTelefono);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 149, -1));

        jBCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, -1));

        jAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jAgregar.setForeground(new java.awt.Color(0, 0, 0));
        jAgregar.setText("Agregar");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 100, -1));

        jDireccion.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(jDireccion);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 240, 90));

        jApellido.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(jApellido);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 149, -1));

        contraseña1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        contraseña1.setText("Apellido:");
        jPanel3.add(contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        contraseña2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseña2.setForeground(new java.awt.Color(255, 255, 255));
        contraseña2.setText("Teléfono:");
        jPanel3.add(contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        contraseña3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        contraseña3.setForeground(new java.awt.Color(255, 255, 255));
        contraseña3.setText("Nivel:");
        jPanel3.add(contraseña3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto" }));
        jNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNivelActionPerformed(evt);
            }
        });
        jPanel3.add(jNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, -1));

        usuario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usuario1.setForeground(new java.awt.Color(255, 255, 255));
        usuario1.setText("Nombre:");
        jPanel3.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        usuario2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usuario2.setForeground(new java.awt.Color(255, 255, 255));
        usuario2.setText("Dirección:");
        jPanel3.add(usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jImagenEst.setBackground(new java.awt.Color(102, 102, 102));
        jImagenEst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jImagenEst.setOpaque(true);
        jPanel3.add(jImagenEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 140, 100));

        jBBuscar.setBackground(new java.awt.Color(247, 210, 130));
        jBBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 90, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 180, 190));

        jCorreo.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setViewportView(jCorreo);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 149, -1));

        jNombre1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setViewportView(jNombre1);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 149, -1));

        jTableListaEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListaEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaEstMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaEst);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 770, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked

        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarMouseClicked

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // ODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
        // TODO add your handling code here:
        String nombre=jNombre1.getText();
        String apellido=jApellido.getText();
        String nivel=jNivel.getSelectedItem().toString();
        int telefono=Integer.parseInt(jTelefono.getText());
        String correo=jCorreo.getText();
        String direccion=jDireccion.getText();
        int idUser=idUserLog;
        try {
            Path pth=Paths.get(imagenPath);
            img=Files.readAllBytes(pth);
            
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
        }
        Estudiante est = new Estudiante(0, nombre, apellido, nivel, telefono,correo,direccion,img,idUserLog);
        EstudiantesQuery query=new EstudiantesQuery();
        query.insetertarEstudiante(est);
    }//GEN-LAST:event_jAgregarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        Imagenes img=new Imagenes();
        imagenPath=img.buscarImagen(jImagenEst);
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTableListaEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaEstMouseClicked
        // TODO add your handling code here:
        int idFila=jTableListaEst.getSelectedRow();
        jNombre1.setText(jTableListaEst.getValueAt(idFila, 1).toString());
        jApellido.setText(jTableListaEst.getValueAt(idFila, 2).toString());
        jNivel.setSelectedItem(jTableListaEst.getValueAt(idFila, 3));
        jTelefono.setText(jTableListaEst.getValueAt(idFila, 4).toString());
        jCorreo.setText(jTableListaEst.getValueAt(idFila, 5).toString());
        jDireccion.setText(jTableListaEst.getValueAt(idFila, 6).toString());
        Image img=((ImageIcon)jTableListaEst.getValueAt(idFila, 7)).getImage().getScaledInstance(jImagenEst.getWidth(),jImagenEst.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imgEst=new ImageIcon(img);
        jImagenEst.setIcon(imgEst);
    }//GEN-LAST:event_jTableListaEstMouseClicked

    private void jNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cerrar;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel contraseña1;
    private javax.swing.JLabel contraseña2;
    private javax.swing.JLabel contraseña3;
    private javax.swing.JButton jAgregar;
    private javax.swing.JTextPane jApellido;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JTextPane jCorreo;
    private javax.swing.JTextPane jDireccion;
    private javax.swing.JLabel jImagenEst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jNivel;
    private javax.swing.JTextPane jNombre1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableListaEst;
    private javax.swing.JTextPane jTelefono;
    public javax.swing.JLabel jUserImgLog;
    public javax.swing.JLabel jUsuarioLog;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    // End of variables declaration//GEN-END:variables
}
